name: Lint

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm Cache Folder
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.15.0

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
      
    - name: Run E2E on Chrome
      uses: cypress-io/github-action@v2
      with:
          browser: chrome
          start: npm run test:e2e:ci
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8000'
